[package]
name = "typkit"
version = "0.2.0"
compiler = "0.12.0"
repository = "https://github.com/kdog3682/typkit"
entrypoint = "src/index.typ"
authors = [
  "Kevin Lee <https://github.com/kdog3682>",
]
license = "MIT"
description = "quick and easy useful utility helpers"
categories = [ "library" ]
keywords = [ "library", "helpers" ]
exclude = [ "manual.pdf", "manual.typ" ]
